insert into ADDRESS (ID, CITY, COUNTRY, LATITUDE, LONGITUDE, STREET_AND_NUMBER) values (1, 'Novi Sad', 'Serbia', 0, 0, 'Kralja Petra 1');
insert into ADDRESS (ID, CITY, COUNTRY, LATITUDE, LONGITUDE, STREET_AND_NUMBER) values (2, 'Novi Sad', 'Serbia', 1, 1, 'Kralja Milana 1');
insert into ADDRESS (ID, CITY, COUNTRY, LATITUDE, LONGITUDE, STREET_AND_NUMBER) values (3, 'Novi Sad', 'Serbia', 2, 2, 'Kralja Aleksandra 1');
INSERT INTO users (D_TYPE,ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHONE_NUMBER,ROLE,FIRST_LOGIN,ADDRESS_ID) VALUES ('ADMIN',1,'admin','admin','admin','pass','21323',1,0,1);
INSERT INTO users (D_TYPE,ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHONE_NUMBER,ROLE,FIRST_LOGIN,ADDRESS_ID) VALUES ('HOME_OWNER',2,'home@owner.com','home','owner','pass','21323',4,0,2);
INSERT INTO users (D_TYPE,ID,EMAIL,FIRST_NAME,LAST_NAME,PASSWORD,PHONE_NUMBER,ROLE,FIRST_LOGIN,ADDRESS_ID) VALUES ('FISHING_INSTRUCTOR',3,'fishing@instructor.com','fishing','instructor','pass','21323',3,0,3);
